packages/testutils/src/serializers/__tests__/blob-serializer.spec.ts, packages/testutils/src/serializers/__tests__/form-data-serializer.spec.ts, packages/testutils/src/serializers/blob-serializer.ts, packages/testutils/src/setupTestUtils.ts
=> feat(testutils): Add blob serializer.

packages/forms/src/FormikEnhancedProvider.tsx, packages/forms/src/FormsProvider.tsx, packages/forms/src/__tests__/FormikDateField.spec.tsx, packages/forms/src/__tests__/FormikEnhanced.spec.tsx, packages/forms/src/__tests__/index.spec.ts, packages/forms/src/__testutils__/renderFormField.tsx, packages/forms/src/__testutils__/renderProvider.tsx, packages/forms/src/index.ts, packages/forms/src/useFormikEnhanced.ts, packages/webpage/ui/Forms.demo.tsx
=> feat(forms): Rename AppFormik to FormikEnhanced.

packages/ui/src/__tests__/index.spec.ts, packages/ui/src/avatar-button/AvatarButton.tsx, packages/ui/src/avatar-button/__tests__/AvatarButton.spec.tsx, packages/ui/src/avatar/AvatarOverrides.ts, packages/ui/src/avatar/__tests__/Avatar.spec.tsx, packages/ui/src/index.ts, packages/ui/src/switch/__tests__/Switch.spec.tsx, packages/ui/src/theme/Color.ts, packages/ui/src/theme/ThemeProvider.tsx, packages/ui/src/theme/__tests__/__snapshots__/ThemeProvider.spec.ts.snap, packages/webpage/DataDisplay.stories.ts, packages/webpage/Inputs.stories.ts, packages/webpage/ui/Avatar.demo.tsx, packages/webpage/ui/AvatarButton.demo.tsx
=> feat(ui): Introduce `AvatarButton`.

packages/lab/src/box/Box.tsx
Added "medium" option for Box component's `borderWidth` prop.
=> feat(lab): [Box] Add medium border width

packages/lab/src/description-item/DescriptionItem.tsx
Discussion link: https://superdispatch.slack.com/archives/C08C96H3L/p1627021420010200
=> feat: [DescriptionItem] Increased space between icon and label

packages/ui/src/info-card/InfoCard.tsx, packages/ui/src/info-card/__tests__/InfoCard.spec.tsx
=> feat(ui): [InfoCard] Make square for fullWidth.

packages/lab/src/box/Box.tsx
Added "medium" option for Box component's `borderRadius` prop.
=> feat(lab): [Box] Add medium border radius variant

packages/dates/src/date-time-utils/DateTimeUtils.ts
updated formatter there was formatter like `March 08 2023` which is now `March 8 2023`
=> chore: [CAR-4247] Updated DateTime formatter

packages/lab/src/index.spec.ts, packages/lab/src/index.ts
=> fix: Export chat components.

packages/ui/src/theme/Color.ts
=> chore: Add Dark200 to deprecated colors and sort colors

packages/dates/src/calendar/Calendar.spec.tsx, packages/dates/src/calendar/Calendar.tsx
Calendar Component style change
**Checklist:**
=> chore: [FRONT-84] Calendar component style change

packages/ui/src/link/LinkOverrides.ts, packages/ui/src/link/__tests__/Link.spec.tsx
Link disabled mode UI issue fixed
**Checklist:**
**JIRA card:**
=> fix: link disabled mode

packages/ui/src/snackbar/Snackbar.stories.tsx, packages/ui/src/snackbar/SnackbarContent.tsx, packages/ui/src/snackbar/__tests__/Snackbar.spec.tsx
New variant 
**Checklist:**
- [] I wrote the necessary tests
**JIRA card:**
[https://superdispatch.atlassian.net/browse/STMS-2273](https://superdispatch.atlassian.net/browse/STMS-2273)
=> feat:[STMS-2273] Update error  Snackbar

packages/ui/src/snackbar/Snackbar.stories.tsx, packages/ui/src/snackbar/SnackbarContent.tsx, packages/ui/src/snackbar/__tests__/Snackbar.spec.tsx
**Checklist:**
**JIRA card:**
[https://superdispatch.atlassian.net/browse/STMS-2273](https://superdispatch.atlassian.net/browse/STMS-2273
)
=> feat:[STMS-2273] Snackbar component aligned for long text messages

packages/ui/src/menu/MenuOverrides.ts, packages/ui/src/menu/__tests__/Menu.spec.tsx
=> feat: [TRST-1447] Added border to Menu component

packages/dates/src/formatted-date/FormattedDate.stories.tsx
Formatted date story file
**Checklist:**
**JIRA card:**
[https://superdispatch.atlassian.net/browse/STMS-2320](https://superdispatch.atlassian.net/browse/STMS-2320
)
=> feat: [STSM-2320] FormattedDate story file-a

packages/dates/src/base-date-picker/BaseDatePicker.tsx
DatePicker stroke color updated
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/FRONT-106
=> feat: [FRONT-106] Updated DatePicker stroke color

packages/ui/src/utils/VisibilityObserver.tsx
=> fix: Resolve issue with useVisibilityObserver on webview

packages/dates/src/calendar/Calendar.spec.tsx, packages/dates/src/calendar/Calendar.tsx
**Checklist:**
**JIRA card:** https://superdispatch.atlassian.net/browse/FRONT-123
=> feat: [FRONT-123] Update current date styles in Calendar component

packages/ui/src/snackbar/SnackbarOverrides.ts, packages/ui/src/snackbar/__tests__/Snackbar.spec.tsx
Updated Snackbar component background color 
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/FRONT-129
=> feat: [FRONT-129] updated Snackbar component background color

.github/workflows/pr.yml, packages/ui/src/number-field/NumberField.tsx
Updated PR.yml github actions
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/CARE-442
=> feat: [CARE-442] Updated PR.yml github actions

packages/dates/src/date-config/DateConfig.tsx, packages/dates/src/date-time-utils/DateTimeUtils.ts
Updated default language to en-US in Date Time
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/CARE-464
Before: 
After:
=> feat: [CARE-464] Updated default language to en-US in Date Time

package.json, packages/ui/src/drawer/Drawer.stories.tsx, packages/ui/src/drawer/DrawerTitle.tsx, patches/@pika+pack+0.5.0.patch, yarn.lock
Align end action to start
**Checklist:**
**JIRA card:**
=> feat(ui): [DrawerTitle] Align end action to start

.gitignore
=> chore: add code-workspace files to gitignore

packages/dates/src/calendar/CalendarQuickSelection.tsx
=> feat(dates): Support title for CalendarQuickSelection

packages/dates/src/date-range-field/DateRangeField.tsx
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/LM-1227
=> feat: [LM-1227] Allow change quantity of monthes for DateRangeField

packages/forms/src/text/FormikTextField.tsx
=> fix: [LM-1496] select on 'enter' Textfield

packages/lab/src/text-box/TextBox.tsx
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/STMS-3520
=> feat: [STMS-3520] Add Disabled variant for TextBox

.github/workflows/pr.yml
=> feat: [PAYM-2217] Update Github Actions setup

packages/lab/src/box/Box.tsx
=> feat: [PAYM-2214]Update Box component

packages/lab/src/file-list-item/__tests__/FileListItem.spec.tsx, packages/ui/src/columns/Columns.tsx
=> feat: [PAYM-2215] Add vertical align to Columns

packages/forms/package.json, packages/lab/package.json, packages/ui/package.json
=> fix: [PAYM-2272] Downgrade superdispatch/hooks to 0.30.0 for web-ui

.storybook/preview.js, packages/ui/src/theme/GlobalStyles.tsx, packages/ui/src/theme/ThemeProvider.tsx
=> chore: [PAYM-2243] added dark mode control to material ui

packages/ui/src/theme/ThemeProvider.tsx
=> fix: [PAYM-2320] fixed tooltip color

packages/ui/src/dialog/Dialog.stories.tsx, packages/ui/src/theme/ThemeProvider.tsx
=> fix:[PAYM-2333] fixed dialog background and button

packages/ui/src/tag/Tag.tsx, packages/ui/src/tag/__tests__/Tag.spec.tsx
=> fix:[PAYM-2331] fixed Tag bold tags

packages/ui/src/checkbox/CheckboxOverrides.tsx, packages/ui/src/checkbox/__tests__/Checkbox.spec.tsx
=> fix: [PAYM-2321] fixed checkbox

packages/ui/src/radio/RadioOverrides.tsx, packages/ui/src/radio/__tests__/Radio.spec.tsx
=> fix: [PAYM-2322] fixed radio buttons

packages/ui/src/switch/SwitchOverrides.ts, packages/ui/src/switch/__tests__/Switch.spec.tsx
=> fix:[ PAYM-2330] fixed switch

packages/lab/src/button/Button.tsx
=> fix:[PAYM-2362] fixed button text color

packages/lab/src/button/Button.tsx
=> feat:[PAYM-2368] updated active color for button

packages/ui/src/checkbox/CheckboxField.tsx, packages/ui/src/radio/RadioField.tsx
=> feat: Add form control props

packages/lab/src/navbar/NavbarList.tsx, packages/ui/src/theme/GlobalStyles.tsx
Updated Global Style and Navbar scrollbar color
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/FRONT-140
=> feat: [FRONT-140] Updated Global Style and Navbar scrollbar color

packages/lab/src/navbar/NavbarItem.tsx, packages/ui/src/info-tooltip/__tests__/InfoTooltip.spec.tsx, packages/ui/src/tooltip/TooltipOverrides.ts, packages/ui/src/tooltip/__tests__/Tooltip.spec.tsx
=> fix:[PAYM-2512] fixed navbar badge colors and tooltip 

packages/ui/src/info-tooltip/__tests__/InfoTooltip.spec.tsx, packages/ui/src/tooltip/TooltipOverrides.ts, packages/ui/src/tooltip/__tests__/Tooltip.spec.tsx
=> fix:[PAYM-2512] fixed tooltip colors

packages/lab/src/navbar/Navbar.tsx
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/STMS-3945
=> fix(Navbar): [STMS-3945] remove scroll from main content

packages/ui/src/app-drawer/AppDrawer.tsx
=> feat(drawer): [STMS-4225] use all Button props for action props

packages/lab/src/button-area/ButtonArea.tsx
**Checklist:**
**JIRA card:**
https://superdispatch.atlassian.net/browse/STMS-4784
=> chore: [STMS-4784] Add children to ButtonArea
